### ISSUE TITLE
Slight differences of the focus points displayed in the plugin and the built-in camera screen

### ISSUE THREAD

**Issue by lethal233** [musselwhizzle/Focus-Points#176]
Hi, 

Firstly I want to say thanks to your dedicated developers. After successfully installing the plug-in, I saw a slight difference of the focus points displayed in the plugin pop-up and the built-in camera screen. I was just wondering whether this can be accepted or not. If it cannot be accepted, is following the "add your own camera" section the next step?

Camera Model: Sony Alpha 7 C II

Your plugin shows:
![image](https://github.com/musselwhizzle/Focus-Points/assets/47763046/015ced3c-0f11-4e3e-88e3-a96efae5469d)

The built-in screen shows:
![IMG_9809](https://github.com/musselwhizzle/Focus-Points/assets/47763046/01c40974-f024-4fc1-8e34-b815e3b60cac)

**Comment by capricorn8** [comment]
I don't have Sony specific AF knowledge, but the following applies to modern mirrorless cameras in general and should be kept in mind when evaluating the plugin result:

1. The plugin relies on documented tags from EXIF metadata (maker notes section) to retrieve AF information. If the camera does not maintain these fields properly because it primarily uses other AF related sections in an undocumented part of maker notes the results of camera (or maker's RAW converter) display and plugin may differ.
I am using OM-1 and can see a similar behavior. For OM-1 predecessors E-M1, E-M5, E-M10 results are identical.

There are other Sony AF visualizers eg. [https://github.com/SK-Hardwired/s_afv](https://github.com/SK-Hardwired/s_afv). 
You might want to check if these show differences in AF position as well.

2. For cameras using contrast AF, the center dot displayed by the plugin is misleading*. The focus point is somewhere inside the red box. Accordingly, on camera display the focus point is somewhere inside the green box. Both red and green boxes in the images do overlap, so in my opinion the difference is acceptable.

* That's why I have removed it for Olympus and OM System cameras. I am not the inventor/author of the plugin so I didn't want to touch the logic for other camera makers.

**Comment by lethal233** [comment]
> I don't have Sony specific AF knowledge, but the following applies to modern mirrorless cameras in general and should be kept in mind when evaluating the plugin result:
> 
> 1. The plugin relies on documented tags from EXIF metadata (maker notes section) to retrieve AF information. If the camera does not maintain these fields properly because it primarily uses other AF related sections in an undocumented part of maker notes the results of camera (or maker's RAW converter) display and plugin may differ.
>    I am using OM-1 and can see a similar behavior. For OM-1 predecessors E-M1, E-M5, E-M10 results are identical.
> 
> There are other Sony AF visualizers eg. https://github.com/SK-Hardwired/s_afv. You might want to check if these show differences in AF position as well.
> 
> 2. For cameras using contrast AF, the center dot displayed by the plugin is misleading*. The focus point is somewhere inside the red box. Accordingly, on camera display the focus point is somewhere inside the green box. Both red and green boxes in the images do overlap, so in my opinion the difference is acceptable.
> 
> *That's why I have removed the center dot for Olympus and OM System cameras. I am neither the inventor/author of the plugin nor do I have specific knowledge about Canon/Nikon/Sony etc. so I didn't want to touch the logic for other camera makers.

Gotcha, thank you very much! I will try the visualizer instead.

**Comment by capricorn8** [comment]
I am reopening this fairly old issue.

I am currently working on the plugin not just to make its operation more user-friendly and provide more information to assess the focus results. See [latest pre-release](https://github.com/capricorn8/Focus-Points/releases/tag/v2.4.902) and accompanying [user documentation](https://github.com/capricorn8/Focus-Points/blob/develop/docs/Focus%20Points.md).

As far as camera support goes, I'm done with Canon, Nikon, Fuji and Olympus - reviewing the implemented focus point logic and comparing the against the reference apps (NX Studio, DPP, etc.).

Next will be Sony.

I'm not a Sony shooter, so my major source for test images is dpreview galleries.

If you are still interested in this plugin and send me the above image, I will investigate the reason for the deviation. Also thank you for the link to Sony AF visualizer!

**Comment by ropma** [comment]
Hallo Karsten,

here you can find two other Sony picture where there is a slight difference:

https://www.dropbox.com/scl/fo/bwzenzlqw0rf4p3k6g7ts/AO3uRVb89lLUVa8mixKQe5w?rlkey=i04g1j4g9k8uh90qz9dkhtsu3&st=7krlasy9&dl=0

If you need more examples or other AF modes, please tell me.
 
Regards Roland

**Comment by capricorn8** [comment]
Hallo Roland,

I'm confident, that the slight deviation in focus display is fixed - at least for A6xxx, A7 and A7R which are currently under investigation.

Do these screenshots show the expected result?

![Image](https://github.com/user-attachments/assets/4ac42994-995c-4147-bd7a-f866c7b0f804)
![Image](https://github.com/user-attachments/assets/3b0e52cc-6b0c-4f9f-a242-d27d9fb7c812)

The same should apply to PDAF point positions. 

BTW, is there any way to check focus/PDAF points against a Sony reference display? I have downloaded Imaging Edge, but the viewer doesn't even display the focus points for many images and no PDAF points at all.

The only possibility of comparison I currently have is the SK-Hardwired app mentioned by the TO and here positions perfectly match.

Face detection is also working:

![Image](https://github.com/user-attachments/assets/41a24901-0d7c-4f45-8a38-78cbeff1cd55)
![Image](https://github.com/user-attachments/assets/e94e0913-5955-4a7e-952a-ef3b7693d69e)

One thing which I don't understand how to handle is the many images captured with AF-S (across various lines and models) that do not have any focus information included. I just cannot believe that AF did accomplish a result here:

![Image](https://github.com/user-attachments/assets/c5ca6014-0ee7-4f1d-a3d0-8520b28497fa)

**Comment by ropma** [comment]
Hello Karsten,

you use  Imaging Edge for displaying the focus points, but you have activate it (icon left to the histogram):

![Image](https://github.com/user-attachments/assets/d685dce7-1a56-40f8-a09c-5e9f4c53f434)

The focus point on your screenshot are better, but still not the same are in IE (see also the screenshot above).

Focus point are only support for the newer Sony cameras. See readme:

>   Sony E-Mount cameras
>      all full frame bodies beginning with α7 III resp. α7R II
>      APS-C
>           α6100, α6400, α6500, α6600, ..

This also applies to Imaging Edge.

**Comment by capricorn8** [comment]
The issue is not that I didn't know how to activate the focus frame display. IE just doesn't display focus points and face detection frames. E.g. for the image of the woman and the child taken with a 7R IV there is nothing. I have many such images taken with a camera later than the ones mentioned in readme.

You are right that the plugin doesn't display the same information in all instances. The IE display isn't as detailed as the plugin's display. See this example:

![Image](https://github.com/user-attachments/assets/d96c5d45-0061-41c1-aba4-2bca5de76658)
![Image](https://github.com/user-attachments/assets/536d4f1d-f0be-4163-9e03-f77cd5fdb468)

The plugin visualizes the information stored in EXIF makernotes. The results are the same as for SK-Hardwired app. For their IE app, Sony might make uses of additional information that has not been decoded yet (or is not even part of EXIF metadata).
For the average camera user, too detailed information might be confusing. However, I don't see how one should easily produce the frames as displayed by IE. If somebody has a got idea, she/he can join this development and implement that.

**Comment by ropma** [comment]
That's strange. 
The focus point are in the EXIF data, because our plugin can display them.

Thus I assume that is a IE problem. I download the raw from the 'woman and the child'  and it is a  "Reduced-resolution image" . If I use the lower RAW size, I get the same problem. The focus point are not displayed within IE.

**Comment by capricorn8** [comment]
If you're interested to use the current version on your images:

My "develop" branch has all the latest changes, the code is a pre-pre-release of V2.5 (only quick regression test pending).

This version includes verified support for all brands/models except Pentax. See [changelog](https://github.com/capricorn8/Focus-Points/blob/develop/docs/changelog.md).

Be sure to have a look at the [user documentation](https://github.com/capricorn8/Focus-Points/blob/develop/docs/Focus%20Points.md) - quite a few things have changed since the original version that existed for many years.

I'm planning to push all the changes to master next week and officially release V2.5.

**Comment by ropma** [comment]
I synced your develop branch. Looks very promising.  I really like the extra infos at the right border.
Thank you

**Comment by capricorn8** [comment]
Glad you like it 😊 In fact, overhauling the UI has been much less effort compared to the effort in making Nikon support complete.  If you talk about "rocket science" - Nikon AF really is! 😄

**Comment by ropma** [comment]
> .. to the effort in making Nikon support complete. If you talk about "rocket science" - Nikon AF really is! 😄

was is all done by reverse engineering or is there a documentation?

**Comment by capricorn8** [comment]
> was is all done by reverse engineering or is there a documentation?

No documentation. Reverse engineering supported by fruitful discussions with ExifTool's Nikon expert. Plus, a lot of manual effort to precisely sizing the PDAF pixel points for the various models. Nikon (by default for DSLRs, but also for the PDAF part in Mirrorless) is using a naming scheme like A1, C6, E9 for PD focus points w/o any information on pixel coordinates...

**Comment by ckyakr** [comment]
The focus point is still off by 50% of the box it's supposed to overlay.  The photo I was checking was shot on a Sony A7R V, and I'm using v2.1.0 of the plugin in Lightroom Classic 14.0.1 (on Win 10 Pro)

![Image](https://github.com/user-attachments/assets/8c4fcb9b-de51-40d9-aeb8-410558fc62c1)

**Comment by capricorn8** [comment]
With the [current pre-release](https://github.com/capricorn8/Focus-Points/releases/tag/v2.4.965) there is a chance that this fixed as well.

I'm careful in my wording, because from Sony there is not suitable reference app to check an individual focus point's position like there is for Nikon, Canon and Olympus/OM. Imaging Edge does not display single focus points but groups of focus points forming a larger focus area (see screen shots in this discussion). For the image you posted I bet it would be a big square box enclosing the 8 small boxes.

The best "reference app" I found is [https://github.com/SK-Hardwired/s_afv](https://github.com/SK-Hardwired/s_afv) suggested by the TO. However, also this app draws focus points which positions not always match the grid of PDAF points. Example (for [OOC JPG from  dpreview gallery](https://www.dpreview.com/sample-galleries/9996097469/sony-a6300-real-world-samples/1277268805)):

![Image](https://github.com/user-attachments/assets/ce67f104-8981-4d34-ba75-ed71ea05e182)

I'm neither a Sony shooter nor do I know enough about the details of Sony AF to judge whether such situations can happen or it's just faulty processing of focus point information. Feedback welcome.

What's the focus point display for your image when using the current version of the plugin?

**Comment by capricorn8** [comment]
Fixed in V3.0.0

**Comment by capricorn8** [comment]
> The focus point on your screenshot are better, but still not the same are in IE (see also the screenshot above).

Rather by chance I came across the fact that newer Sony models feature a tag "FocusFrameSize", which gives exactly the dimensions of the focus box visible in IE. It's implemented and will be part of the next update (after summer).

![Image](https://github.com/user-attachments/assets/62e17a6a-d104-451e-81a2-9cc93bacb268)

![Image](https://github.com/user-attachments/assets/98eb059f-9c9d-4173-a06e-8f903db7493d)

**Comment by ropma** [comment]
Hi Karsten,

thank you of the update.
I'll test it as soon as the new version is available.

Regards Roland

**Comment by capricorn8** [comment]
@ropma There's a pre-release in my develop channel that contains the fix for this issue:

[https://github.com/capricorn8/Focus-Points/releases/tag/v3.1_pre3](url)
